- hosts: all
  tasks:
    - name: Add the GPG key for Docker
      shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes'

    - name: Add the repository to fetch the docker package
      shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

    - package:
        name:
          - docker
          - python3-docker
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
          - python3-setuptools
          - docker-ce
        state: present

    - name: Install the Docker module for Python, required by ansible
      pip:
        name: docker
    - name: Pull an image
      community.docker.docker_image:
        name: ghost
        source: pull    
    - name: Create a data container
      community.docker.docker_container:
        name: docker_img
        image: ghost
        state: started
        ports:
          - "3001:2368"
        env:
            NODE_ENV=development
