- hosts: all
  tasks:
    - package:
        name:
          - tomcat9
        state: present
    - name: Create a data container
      docker_container:
        name: docker_img
        image: https://hub.docker.com/_/ghost/
