- hosts: all
  tasks:
    - package:
        name:
          - docker
          - python3-docker
        state: present
        
    - name: Create a data container
      community.docker.docker_container:
        name: docker_img
        source: pull
        image: ghost
        state: started
