- hosts: all
  tasks:
    - package:
        name:
          - tomcat9
        state: present
    - name: Webapps
      ansible.builtin.copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/sample.war
        mode: '0644'


      
