- hosts: all
  tasks:
    - package:
        name:
          - tomcat9
        state: present
    - name: Webapps
      ansible.builtin.get_url:
        url: https://github.com/downloads/CrazySmiley/ansible-form/sample.war
        dest: /var/lib/tomcat9/webapps/sample.war
        mode: '0444'

      
