- hosts: all
  tasks:
    - package:
        name:
          - tomcat9
        state: present
    - webapps:
      ansible.builtin.get_url:
        url: https://github.com/CrazySmiley/ansible-form/blob/main/sample.war
        dest: /var/lib/tomcat9/webapps/sample.war
        mode: '0440'
